BusinessType.create(name: "Barber")
BusinessType.create(name: "Hair Salon")
BusinessType.create(name: "Tattoo and Piercing")
BusinessType.create(name: "Nail Salon")
BusinessType.create(name: "Spa")
BusinessType.create(name: "Hair Braiding")
BusinessType.create(name: "Other")